# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rpc.pubsub_pb2 as pubsub__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pubsub_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class pubsubStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pubsubServe = channel.unary_unary(
                '/rpc_package.pubsub/pubsubServe',
                request_serializer=pubsub__pb2.mes2server.SerializeToString,
                response_deserializer=pubsub__pb2.mes2client.FromString,
                _registered_method=True)


class pubsubServicer(object):
    """定义服务
    """

    def pubsubServe(self, request, context):
        """定义服务的接口
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pubsubServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pubsubServe': grpc.unary_unary_rpc_method_handler(
                    servicer.pubsubServe,
                    request_deserializer=pubsub__pb2.mes2server.FromString,
                    response_serializer=pubsub__pb2.mes2client.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc_package.pubsub', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rpc_package.pubsub', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class pubsub(object):
    """定义服务
    """

    @staticmethod
    def pubsubServe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rpc_package.pubsub/pubsubServe',
            pubsub__pb2.mes2server.SerializeToString,
            pubsub__pb2.mes2client.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
